server:
  port: 8080

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
management:
  health:
    defaults:
      enabled: false
      
spring:
  datasource:
    url: jdbc:postgresql://postgresql.prueba-redhat.svc.cluster.local:5432/test
    username: redhat
    password: redhat